development:
  foursquare:
    client_id: "XGEONZHLJFRGF3NKQFVCEPLHJFNLX1HH5SMSJBWAGGXJJHAL"
    client_secret: "R2EHQYB2OFSHDOUPCVEM03ZKELEUGAE3SX5POJBGLK4ZDVKO"
  instagram:
    client_id: "c7fa52f39645438d96c23f06c384e3c8"
    client_secret: "9b849fcb8e6348ceb8b71c3818d20f62"