development:
  foursquare:
    client_id: 
    client_secret: 
  instagram:
    client_id: 
    client_secret: 
    redirect_uri: "http://localhost:3000/instagram/redirect"
production:
  foursquare:
    client_id: 
    client_secret: 
  instagram:
    client_id: 
    client_secret: 
    redirect_uri: "http://localhost:3000/instagram/redirect"